### ISSUE TITLE
[Documentation]: Pictures

### ISSUE THREAD

**Issue by thomasthaddeus** [thomasthaddeus/DS-Competition#14]
### Which file/page is this issue related to?

docs

### Please describe the problem with the documentation. What were you expecting to see?

- [x] [docs](./docs/venv_setup.md)

### Do you have a suggested fix?

- [x] need to add pics to img for the previous task

**Comment by TheMightiestCaz** [comment]
Do you want the pictures added in directly to the MD file or do you want to create a separate folder that has all the images in it and we reference it that way?

**Comment by thomasthaddeus** [comment]
They're already in a separate folder that i referenced in the md document.

**Comment by thomasthaddeus** [comment]
> Do you want the pictures added in directly to the MD file or do you want to create a separate folder that has all the images in it and we reference it that way?

for future reference its the second one!
